services:
  openrouteservice:
    image: openrouteservice/openrouteservice:v9.9.0
    container_name: ors-app
    ports:
      - "8080:8082"
    environment:
      XMS: "1g"
      XMX: "3g"
      ORS_ENGINE_PROFILE_DEFAULT_BUILD_SOURCE_FILE: "/home/ors/files/jiangsu-latest.osm.pbf"
      ORS_ENGINE_PROFILES_DRIVING_CAR_ENABLED: "true"
      BUILD_GRAPHS: "True"
    volumes:
      - ./ors-docker/config:/home/ors/config
      - ./ors-docker/elevation_cache:/home/ors/elevation_cache
      - ./ors-docker/graphs:/home/ors/graphs
      - ./ors-docker/files:/home/ors/files
      - ./ors-docker/logs:/home/ors/logs
    restart: unless-stopped
